### ISSUE TITLE
EnvFile writer fails to handle comments on the .env file

### ISSUE THREAD

**Issue by 3m1n3nc3** [wintercms/laravel-config-writer#1]
The `EnvFile` writer produces inconsistent results when working with commented variables.

The following entry on the .env file:

```ENV_KEY="value" #Some comment```

Will produce the following results:

```ENV_KEY="value #Some comment"```

**Comment by LukeTowers** [comment]
It should work with comments on their own line as a temporary workaround:

```
#Some comment
ENV_KEY="value"
```

**Comment by LukeTowers** [comment]
@jaxwilko are you able to take a look?

**Comment by jaxwilko** [comment]
@LukeTowers yeah i can take a look tomorrow :)
